name: Build

on:
  push:
    branches:
    - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: docs/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Build Antora site
      run: make docs-build
    - name: Push Antora build to gh-pages
      run: .github/antora-gh-pages.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
